# Generated by Django 4.0.6 on 2022-10-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='currentYear',
            field=models.DateField(),
        ),
    ]
