# Generated by Django 4.0.6 on 2022-09-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_msg_alter_profile_jobdescription1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userid',
        ),
    ]
