# Generated by Django 4.0.6 on 2022-10-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_education_currentyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='currentYear',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
