# Generated by Django 4.0.6 on 2022-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_profile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currentYear1',
            field=models.DateField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currentYear2',
            field=models.DateField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='highSchoolPassingYear',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='highSchoolStartingYear',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intermediatePassingYear',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intermediateStartingYear',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobEndDate1',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobEndDate2',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobEndDate3',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobEndDate4',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobEndDate5',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobStartDate1',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobStartDate2',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobStartDate3',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobStartDate4',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobStartDate5',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projectEndDate1',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projectEndDate2',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projectEndDate3',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projectEndDate4',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projectEndDate5',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projectStartDate1',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projectStartDate2',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projectStartDate3',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projectStartDate4',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projectStartDate5',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='univPassingYear1',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='univPassingYear2',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='univStartingYear1',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='univStartingYear2',
            field=models.DateField(blank=True, max_length=20),
        ),
    ]
